spring:
    datasource:
        url: jdbc:mariadb://localhost/mariadb
        driverClassName: org.mariadb.jdbc.Driver
        username: root
        password: root
       #  url: jdbc:mariadb://mydatabase.c4h89kt7p5q1.ap-northeast-2.rds.amazonaws.com/mydatabase
       #  driverClassName: org.mariadb.jdbc.Driver
       #  username: demoproject
       #  password: demodemo22
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: update
        # show-sql: true
        # properties:
        #    hibernate:
        #        format_sql: true
auth:    
  jwtExpirationMs: 600000
  jwtSecret: JWTSuperSecretKey    
        
