spring:
  datasource:
    url: jdbc:mariadb://mydatabase.c4h89kt7p5q1.ap-northeast-2.rds.amazonaws.com/mydatabase
    driverClassName: org.mariadb.jdbc.Driver
    username: demoproject
    password: demoproject
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8080