spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/mariadb
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: root
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8080