spring:
    datasource:
        url: jdbc:mariadb://mydatabase.c4h89kt7p5q1.ap-northeast-2.rds.amazonaws.com/myinstance
        driverClassName: org.mariadb.jdbc.Driver
        username: demoproject
        password: demoproject
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: update
        # show-sql: true
        # properties:
        #    hibernate:
        #        format_sql: true
